// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mathService.proto

package mathService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	X                    int64    `protobuf:"zigzag64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"zigzag64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AddRequest) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type AddResponse struct {
	Addition             int64    `protobuf:"zigzag64,1,opt,name=addition,proto3" json:"addition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetAddition() int64 {
	if m != nil {
		return m.Addition
	}
	return 0
}

type AverageRequest struct {
	Array                []float64 `protobuf:"fixed64,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AverageRequest) Reset()         { *m = AverageRequest{} }
func (m *AverageRequest) String() string { return proto.CompactTextString(m) }
func (*AverageRequest) ProtoMessage()    {}
func (*AverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{2}
}

func (m *AverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageRequest.Unmarshal(m, b)
}
func (m *AverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageRequest.Marshal(b, m, deterministic)
}
func (m *AverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageRequest.Merge(m, src)
}
func (m *AverageRequest) XXX_Size() int {
	return xxx_messageInfo_AverageRequest.Size(m)
}
func (m *AverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AverageRequest proto.InternalMessageInfo

func (m *AverageRequest) GetArray() []float64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type AverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{3}
}

func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (m *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(m, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

type MaxRequest struct {
	Array                []float64 `protobuf:"fixed64,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MaxRequest) Reset()         { *m = MaxRequest{} }
func (m *MaxRequest) String() string { return proto.CompactTextString(m) }
func (*MaxRequest) ProtoMessage()    {}
func (*MaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{4}
}

func (m *MaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxRequest.Unmarshal(m, b)
}
func (m *MaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxRequest.Marshal(b, m, deterministic)
}
func (m *MaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxRequest.Merge(m, src)
}
func (m *MaxRequest) XXX_Size() int {
	return xxx_messageInfo_MaxRequest.Size(m)
}
func (m *MaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaxRequest proto.InternalMessageInfo

func (m *MaxRequest) GetArray() []float64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type MaxResponse struct {
	Maximum              float64  `protobuf:"fixed64,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxResponse) Reset()         { *m = MaxResponse{} }
func (m *MaxResponse) String() string { return proto.CompactTextString(m) }
func (*MaxResponse) ProtoMessage()    {}
func (*MaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{5}
}

func (m *MaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxResponse.Unmarshal(m, b)
}
func (m *MaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxResponse.Marshal(b, m, deterministic)
}
func (m *MaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxResponse.Merge(m, src)
}
func (m *MaxResponse) XXX_Size() int {
	return xxx_messageInfo_MaxResponse.Size(m)
}
func (m *MaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaxResponse proto.InternalMessageInfo

func (m *MaxResponse) GetMaximum() float64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type MinRequest struct {
	Array                []float64 `protobuf:"fixed64,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MinRequest) Reset()         { *m = MinRequest{} }
func (m *MinRequest) String() string { return proto.CompactTextString(m) }
func (*MinRequest) ProtoMessage()    {}
func (*MinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{6}
}

func (m *MinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinRequest.Unmarshal(m, b)
}
func (m *MinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinRequest.Marshal(b, m, deterministic)
}
func (m *MinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinRequest.Merge(m, src)
}
func (m *MinRequest) XXX_Size() int {
	return xxx_messageInfo_MinRequest.Size(m)
}
func (m *MinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MinRequest proto.InternalMessageInfo

func (m *MinRequest) GetArray() []float64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type MinResponse struct {
	Minimum              float64  `protobuf:"fixed64,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinResponse) Reset()         { *m = MinResponse{} }
func (m *MinResponse) String() string { return proto.CompactTextString(m) }
func (*MinResponse) ProtoMessage()    {}
func (*MinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{7}
}

func (m *MinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinResponse.Unmarshal(m, b)
}
func (m *MinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinResponse.Marshal(b, m, deterministic)
}
func (m *MinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinResponse.Merge(m, src)
}
func (m *MinResponse) XXX_Size() int {
	return xxx_messageInfo_MinResponse.Size(m)
}
func (m *MinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MinResponse proto.InternalMessageInfo

func (m *MinResponse) GetMinimum() float64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

type SumRequest struct {
	Array                []float64 `protobuf:"fixed64,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{8}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetArray() []float64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type SumResponse struct {
	SumArrayValues       float64  `protobuf:"fixed64,1,opt,name=sumArrayValues,proto3" json:"sumArrayValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{9}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSumArrayValues() float64 {
	if m != nil {
		return m.SumArrayValues
	}
	return 0
}

type SortRequest struct {
	Array                []float64 `protobuf:"fixed64,1,rep,packed,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SortRequest) Reset()         { *m = SortRequest{} }
func (m *SortRequest) String() string { return proto.CompactTextString(m) }
func (*SortRequest) ProtoMessage()    {}
func (*SortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{10}
}

func (m *SortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortRequest.Unmarshal(m, b)
}
func (m *SortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortRequest.Marshal(b, m, deterministic)
}
func (m *SortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortRequest.Merge(m, src)
}
func (m *SortRequest) XXX_Size() int {
	return xxx_messageInfo_SortRequest.Size(m)
}
func (m *SortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SortRequest proto.InternalMessageInfo

func (m *SortRequest) GetArray() []float64 {
	if m != nil {
		return m.Array
	}
	return nil
}

type SortResponse struct {
	SortedArray          []float64 `protobuf:"fixed64,1,rep,packed,name=sortedArray,proto3" json:"sortedArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SortResponse) Reset()         { *m = SortResponse{} }
func (m *SortResponse) String() string { return proto.CompactTextString(m) }
func (*SortResponse) ProtoMessage()    {}
func (*SortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_decbe17beb08d07c, []int{11}
}

func (m *SortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortResponse.Unmarshal(m, b)
}
func (m *SortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortResponse.Marshal(b, m, deterministic)
}
func (m *SortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortResponse.Merge(m, src)
}
func (m *SortResponse) XXX_Size() int {
	return xxx_messageInfo_SortResponse.Size(m)
}
func (m *SortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SortResponse proto.InternalMessageInfo

func (m *SortResponse) GetSortedArray() []float64 {
	if m != nil {
		return m.SortedArray
	}
	return nil
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "mathService.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "mathService.AddResponse")
	proto.RegisterType((*AverageRequest)(nil), "mathService.AverageRequest")
	proto.RegisterType((*AverageResponse)(nil), "mathService.AverageResponse")
	proto.RegisterType((*MaxRequest)(nil), "mathService.MaxRequest")
	proto.RegisterType((*MaxResponse)(nil), "mathService.MaxResponse")
	proto.RegisterType((*MinRequest)(nil), "mathService.MinRequest")
	proto.RegisterType((*MinResponse)(nil), "mathService.MinResponse")
	proto.RegisterType((*SumRequest)(nil), "mathService.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "mathService.SumResponse")
	proto.RegisterType((*SortRequest)(nil), "mathService.SortRequest")
	proto.RegisterType((*SortResponse)(nil), "mathService.SortResponse")
}

func init() { proto.RegisterFile("mathService.proto", fileDescriptor_decbe17beb08d07c) }

var fileDescriptor_decbe17beb08d07c = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xbd, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xeb, 0x06, 0x28, 0xba, 0x54, 0x05, 0xbc, 0x10, 0x02, 0x43, 0x15, 0xa1, 0x52, 0x40,
	0xea, 0xc0, 0xc7, 0x52, 0x89, 0x21, 0x0c, 0x6c, 0x5d, 0x12, 0x89, 0xdd, 0x60, 0x0b, 0x2c, 0xe1,
	0xa4, 0x38, 0x49, 0x95, 0xee, 0xfc, 0xe1, 0xc8, 0xb1, 0xf3, 0x51, 0x53, 0xa9, 0x8c, 0x77, 0xf7,
	0xde, 0x2f, 0x27, 0xbf, 0x0b, 0x9c, 0x08, 0x92, 0x7f, 0xc6, 0x4c, 0xae, 0xf8, 0x3b, 0x9b, 0x2d,
	0x65, 0x9a, 0xa7, 0xd8, 0xed, 0xb4, 0x82, 0x29, 0x40, 0x48, 0x69, 0xc4, 0xbe, 0x0b, 0x96, 0xe5,
	0x78, 0x08, 0xa8, 0xf4, 0xd0, 0x18, 0x4d, 0x71, 0x84, 0x4a, 0x55, 0xad, 0xbd, 0xbe, 0xae, 0xd6,
	0xc1, 0x35, 0xb8, 0x95, 0x32, 0x5b, 0xa6, 0x49, 0xc6, 0xb0, 0x0f, 0x87, 0x84, 0x52, 0x9e, 0xf3,
	0x34, 0x31, 0x8e, 0xa6, 0x0e, 0x6e, 0x60, 0x14, 0xae, 0x98, 0x24, 0x1f, 0xac, 0x06, 0x7b, 0xb0,
	0x4f, 0xa4, 0x24, 0x6b, 0x0f, 0x8d, 0x9d, 0x29, 0x7a, 0xee, 0x1f, 0xa3, 0x48, 0x37, 0x82, 0x5b,
	0x38, 0x6a, 0xb4, 0x06, 0xed, 0xc1, 0x80, 0xe8, 0x56, 0x45, 0x46, 0x51, 0x5d, 0x06, 0x13, 0x80,
	0x05, 0x29, 0x77, 0x43, 0xaf, 0xc0, 0xad, 0x74, 0x2d, 0x50, 0x90, 0x92, 0x8b, 0x42, 0xd4, 0x40,
	0x53, 0x56, 0x40, 0x9e, 0xfc, 0x0f, 0xa8, 0x74, 0x1d, 0x20, 0x4f, 0x36, 0x80, 0xba, 0x54, 0xc0,
	0xb8, 0x10, 0xbb, 0x81, 0x8f, 0xe0, 0x56, 0x3a, 0x03, 0x9c, 0xc0, 0x28, 0x2b, 0x44, 0xa8, 0x46,
	0xaf, 0xe4, 0xab, 0x60, 0x99, 0xe1, 0x5a, 0x5d, 0xb5, 0x47, 0x9c, 0xca, 0x7c, 0x37, 0xff, 0x01,
	0x86, 0x5a, 0x68, 0x3e, 0x70, 0x09, 0x6e, 0x96, 0xca, 0x9c, 0xd1, 0xd0, 0xd2, 0x77, 0xdb, 0x77,
	0x3f, 0x8e, 0x7a, 0xb8, 0xe6, 0x3a, 0xf0, 0x1c, 0x9c, 0x90, 0x52, 0x7c, 0x3a, 0xeb, 0x5e, 0x51,
	0x7b, 0x2f, 0xbe, 0xf7, 0x77, 0xa0, 0xbf, 0x17, 0xf4, 0xf0, 0x0b, 0x0c, 0x4c, 0xb0, 0xf8, 0x7c,
	0x53, 0xb6, 0x71, 0x1a, 0xfe, 0xc5, 0xf6, 0x61, 0xc3, 0x99, 0x83, 0xb3, 0x20, 0xa5, 0xb5, 0x43,
	0x7b, 0x05, 0xd6, 0x0e, 0x9d, 0xd8, 0x8d, 0x97, 0x27, 0xb6, 0xb7, 0x09, 0xdc, 0xf6, 0xb6, 0x09,
	0x6b, 0x6f, 0x5c, 0x08, 0xcb, 0xdb, 0x66, 0x6b, 0x79, 0x3b, 0x61, 0x06, 0x3d, 0xfc, 0x04, 0x7b,
	0xea, 0xf5, 0xb1, 0xa5, 0x69, 0x93, 0xf3, 0xcf, 0xb6, 0x4c, 0x6a, 0xfb, 0xdb, 0x41, 0xf5, 0xa3,
	0xde, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x50, 0xff, 0xad, 0xa8, 0xbd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MathServiceClient is the client API for MathService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MathServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Average(ctx context.Context, in *AverageRequest, opts ...grpc.CallOption) (*AverageResponse, error)
	Max(ctx context.Context, in *MaxRequest, opts ...grpc.CallOption) (*MaxResponse, error)
	Min(ctx context.Context, in *MinRequest, opts ...grpc.CallOption) (*MinResponse, error)
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error)
}

type mathServiceClient struct {
	cc *grpc.ClientConn
}

func NewMathServiceClient(cc *grpc.ClientConn) MathServiceClient {
	return &mathServiceClient{cc}
}

func (c *mathServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/mathService.MathService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Average(ctx context.Context, in *AverageRequest, opts ...grpc.CallOption) (*AverageResponse, error) {
	out := new(AverageResponse)
	err := c.cc.Invoke(ctx, "/mathService.MathService/Average", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Max(ctx context.Context, in *MaxRequest, opts ...grpc.CallOption) (*MaxResponse, error) {
	out := new(MaxResponse)
	err := c.cc.Invoke(ctx, "/mathService.MathService/Max", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Min(ctx context.Context, in *MinRequest, opts ...grpc.CallOption) (*MinResponse, error) {
	out := new(MinResponse)
	err := c.cc.Invoke(ctx, "/mathService.MathService/Min", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/mathService.MathService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathServiceClient) Sort(ctx context.Context, in *SortRequest, opts ...grpc.CallOption) (*SortResponse, error) {
	out := new(SortResponse)
	err := c.cc.Invoke(ctx, "/mathService.MathService/Sort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathServiceServer is the server API for MathService service.
type MathServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Average(context.Context, *AverageRequest) (*AverageResponse, error)
	Max(context.Context, *MaxRequest) (*MaxResponse, error)
	Min(context.Context, *MinRequest) (*MinResponse, error)
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	Sort(context.Context, *SortRequest) (*SortResponse, error)
}

// UnimplementedMathServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMathServiceServer struct {
}

func (*UnimplementedMathServiceServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedMathServiceServer) Average(ctx context.Context, req *AverageRequest) (*AverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Average not implemented")
}
func (*UnimplementedMathServiceServer) Max(ctx context.Context, req *MaxRequest) (*MaxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Max not implemented")
}
func (*UnimplementedMathServiceServer) Min(ctx context.Context, req *MinRequest) (*MinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Min not implemented")
}
func (*UnimplementedMathServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedMathServiceServer) Sort(ctx context.Context, req *SortRequest) (*SortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sort not implemented")
}

func RegisterMathServiceServer(s *grpc.Server, srv MathServiceServer) {
	s.RegisterService(&_MathService_serviceDesc, srv)
}

func _MathService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathService.MathService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Average_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Average(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathService.MathService/Average",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Average(ctx, req.(*AverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Max_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Max(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathService.MathService/Max",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Max(ctx, req.(*MaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Min_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Min(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathService.MathService/Min",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Min(ctx, req.(*MinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathService.MathService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathService_Sort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathServiceServer).Sort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mathService.MathService/Sort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathServiceServer).Sort(ctx, req.(*SortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MathService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mathService.MathService",
	HandlerType: (*MathServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MathService_Add_Handler,
		},
		{
			MethodName: "Average",
			Handler:    _MathService_Average_Handler,
		},
		{
			MethodName: "Max",
			Handler:    _MathService_Max_Handler,
		},
		{
			MethodName: "Min",
			Handler:    _MathService_Min_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _MathService_Sum_Handler,
		},
		{
			MethodName: "Sort",
			Handler:    _MathService_Sort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mathService.proto",
}
