apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: server-deployment
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: math-service-server:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: math-service
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: math-service
spec:
  selector:
    app: server
  ports:
  - port: 9090
    targetPort: math-service